# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jigyasa_mcp import dpSearch_pb2 as dpSearch__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dpSearch_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JigyasaDataPlaneServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Index = channel.unary_unary(
                '/jigyasa_dp_search.JigyasaDataPlaneService/Index',
                request_serializer=dpSearch__pb2.IndexRequest.SerializeToString,
                response_deserializer=dpSearch__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.Lookup = channel.unary_unary(
                '/jigyasa_dp_search.JigyasaDataPlaneService/Lookup',
                request_serializer=dpSearch__pb2.LookupRequest.SerializeToString,
                response_deserializer=dpSearch__pb2.LookupResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/jigyasa_dp_search.JigyasaDataPlaneService/Query',
                request_serializer=dpSearch__pb2.QueryRequest.SerializeToString,
                response_deserializer=dpSearch__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.DeleteByQuery = channel.unary_unary(
                '/jigyasa_dp_search.JigyasaDataPlaneService/DeleteByQuery',
                request_serializer=dpSearch__pb2.DeleteByQueryRequest.SerializeToString,
                response_deserializer=dpSearch__pb2.DeleteByQueryResponse.FromString,
                _registered_method=True)
        self.UpdateSchema = channel.unary_unary(
                '/jigyasa_dp_search.JigyasaDataPlaneService/UpdateSchema',
                request_serializer=dpSearch__pb2.UpdateSchemaRequest.SerializeToString,
                response_deserializer=dpSearch__pb2.UpdateSchemaResponse.FromString,
                _registered_method=True)
        self.CreateCollection = channel.unary_unary(
                '/jigyasa_dp_search.JigyasaDataPlaneService/CreateCollection',
                request_serializer=dpSearch__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=dpSearch__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.CloseCollection = channel.unary_unary(
                '/jigyasa_dp_search.JigyasaDataPlaneService/CloseCollection',
                request_serializer=dpSearch__pb2.CloseCollectionRequest.SerializeToString,
                response_deserializer=dpSearch__pb2.CloseCollectionResponse.FromString,
                _registered_method=True)
        self.OpenCollection = channel.unary_unary(
                '/jigyasa_dp_search.JigyasaDataPlaneService/OpenCollection',
                request_serializer=dpSearch__pb2.OpenCollectionRequest.SerializeToString,
                response_deserializer=dpSearch__pb2.OpenCollectionResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/jigyasa_dp_search.JigyasaDataPlaneService/ListCollections',
                request_serializer=dpSearch__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=dpSearch__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/jigyasa_dp_search.JigyasaDataPlaneService/Health',
                request_serializer=dpSearch__pb2.HealthRequest.SerializeToString,
                response_deserializer=dpSearch__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ForceMerge = channel.unary_unary(
                '/jigyasa_dp_search.JigyasaDataPlaneService/ForceMerge',
                request_serializer=dpSearch__pb2.ForceMergeRequest.SerializeToString,
                response_deserializer=dpSearch__pb2.ForceMergeResponse.FromString,
                _registered_method=True)
        self.Count = channel.unary_unary(
                '/jigyasa_dp_search.JigyasaDataPlaneService/Count',
                request_serializer=dpSearch__pb2.CountRequest.SerializeToString,
                response_deserializer=dpSearch__pb2.CountResponse.FromString,
                _registered_method=True)


class JigyasaDataPlaneServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Index(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteByQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCollection(self, request, context):
        """Collection lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceMerge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Count(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JigyasaDataPlaneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Index': grpc.unary_unary_rpc_method_handler(
                    servicer.Index,
                    request_deserializer=dpSearch__pb2.IndexRequest.FromString,
                    response_serializer=dpSearch__pb2.IndexResponse.SerializeToString,
            ),
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=dpSearch__pb2.LookupRequest.FromString,
                    response_serializer=dpSearch__pb2.LookupResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=dpSearch__pb2.QueryRequest.FromString,
                    response_serializer=dpSearch__pb2.QueryResponse.SerializeToString,
            ),
            'DeleteByQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteByQuery,
                    request_deserializer=dpSearch__pb2.DeleteByQueryRequest.FromString,
                    response_serializer=dpSearch__pb2.DeleteByQueryResponse.SerializeToString,
            ),
            'UpdateSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSchema,
                    request_deserializer=dpSearch__pb2.UpdateSchemaRequest.FromString,
                    response_serializer=dpSearch__pb2.UpdateSchemaResponse.SerializeToString,
            ),
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=dpSearch__pb2.CreateCollectionRequest.FromString,
                    response_serializer=dpSearch__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'CloseCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseCollection,
                    request_deserializer=dpSearch__pb2.CloseCollectionRequest.FromString,
                    response_serializer=dpSearch__pb2.CloseCollectionResponse.SerializeToString,
            ),
            'OpenCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenCollection,
                    request_deserializer=dpSearch__pb2.OpenCollectionRequest.FromString,
                    response_serializer=dpSearch__pb2.OpenCollectionResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=dpSearch__pb2.ListCollectionsRequest.FromString,
                    response_serializer=dpSearch__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=dpSearch__pb2.HealthRequest.FromString,
                    response_serializer=dpSearch__pb2.HealthResponse.SerializeToString,
            ),
            'ForceMerge': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceMerge,
                    request_deserializer=dpSearch__pb2.ForceMergeRequest.FromString,
                    response_serializer=dpSearch__pb2.ForceMergeResponse.SerializeToString,
            ),
            'Count': grpc.unary_unary_rpc_method_handler(
                    servicer.Count,
                    request_deserializer=dpSearch__pb2.CountRequest.FromString,
                    response_serializer=dpSearch__pb2.CountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jigyasa_dp_search.JigyasaDataPlaneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jigyasa_dp_search.JigyasaDataPlaneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JigyasaDataPlaneService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Index(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigyasa_dp_search.JigyasaDataPlaneService/Index',
            dpSearch__pb2.IndexRequest.SerializeToString,
            dpSearch__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigyasa_dp_search.JigyasaDataPlaneService/Lookup',
            dpSearch__pb2.LookupRequest.SerializeToString,
            dpSearch__pb2.LookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigyasa_dp_search.JigyasaDataPlaneService/Query',
            dpSearch__pb2.QueryRequest.SerializeToString,
            dpSearch__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteByQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigyasa_dp_search.JigyasaDataPlaneService/DeleteByQuery',
            dpSearch__pb2.DeleteByQueryRequest.SerializeToString,
            dpSearch__pb2.DeleteByQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigyasa_dp_search.JigyasaDataPlaneService/UpdateSchema',
            dpSearch__pb2.UpdateSchemaRequest.SerializeToString,
            dpSearch__pb2.UpdateSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigyasa_dp_search.JigyasaDataPlaneService/CreateCollection',
            dpSearch__pb2.CreateCollectionRequest.SerializeToString,
            dpSearch__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigyasa_dp_search.JigyasaDataPlaneService/CloseCollection',
            dpSearch__pb2.CloseCollectionRequest.SerializeToString,
            dpSearch__pb2.CloseCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigyasa_dp_search.JigyasaDataPlaneService/OpenCollection',
            dpSearch__pb2.OpenCollectionRequest.SerializeToString,
            dpSearch__pb2.OpenCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigyasa_dp_search.JigyasaDataPlaneService/ListCollections',
            dpSearch__pb2.ListCollectionsRequest.SerializeToString,
            dpSearch__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigyasa_dp_search.JigyasaDataPlaneService/Health',
            dpSearch__pb2.HealthRequest.SerializeToString,
            dpSearch__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForceMerge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigyasa_dp_search.JigyasaDataPlaneService/ForceMerge',
            dpSearch__pb2.ForceMergeRequest.SerializeToString,
            dpSearch__pb2.ForceMergeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Count(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigyasa_dp_search.JigyasaDataPlaneService/Count',
            dpSearch__pb2.CountRequest.SerializeToString,
            dpSearch__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
